spring:
  application:
    name: voisk
  datasource:
    url: jdbc:mysql://localhost:3306/voisk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: # DB 비밀번호 입력
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
