spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: voisk
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
