spring:
  datasource:
    mysql:
      url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/voisk_vector?sslmode=disable}
      username: ${POSTGRES_USERNAME:admin}
      password: ${POSTGRES_PASSWORD:1234}
      driver-class-name: org.postgresql.Driver

embed:
  server:
    url: http://localhost:8000

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
